# Generated by Django 3.0 on 2019-12-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=4),
        ),
    ]
