# Generated by Django 3.0 on 2019-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20191213_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='group',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=4),
        ),
    ]
