# Generated by Django 3.0 on 2019-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20191215_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='group',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=4),
        ),
    ]
