# Generated by Django 3.0 on 2019-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20191215_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='group',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], max_length=1),
        ),
    ]
